# Generated by Django 4.2.4 on 2023-08-15 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="reviwe_text",
            new_name="review_text",
        ),
    ]
